name: SonarCloud and Docker Build

on:
  push:
    branches:
      - develop

jobs:
  sonarcloud_analysis:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token de GitHub necesario para obtener información de PR, si corresponde
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Token de acceso a SonarCloud

  docker_build:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    needs: sonarcloud_analysis
    steps:
      - uses: actions/checkout@v2

      - name: Docker Build and Push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  # Nombre de usuario de Docker Hub
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  # Contraseña de Docker Hub
        run: |
          docker build -t yourdockerhubusername/yourimage:latest .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push valery2024/myapp:v1.0
