name: SonarCloud  + Docker Hub
on:
push:
 branches:
      - develop
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Setup
        run: npm ci
      - name: Test
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  
      #DOCKER HUB
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
  
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ms_content_moderator_fe:latest .
  
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ms_content_moderator_fe:latest
